version: "3"
services:
    web:
        container_name: mongoBoilerplateService
        build:
            dockerfile: Dockerfile.dev
            context: .
        depends_on:
            - db
        ports:
            - "3000:3000"
        volumes:
            - .:/server
        environment:
            - MONGO_HOST=mongodb://db:27017
            - MONGO_DB=sample-app
            - SOCKET_CORS=http://localhost:3001
            - APPLICATION_SERVER_PORT=3001
            - APP_FORCE_SHUTDOWN_SECOND=30

    # Database
    db:
        container_name: mongoBoilerplateMongo
        image: mongo
        ports:
            - "27017:27017"
        restart: always
